image: gradle:jdk8

before_script:
  - wget -q https://courses.cs.washington.edu/courses/cse373/19wi/files/homework/scripts/hw2/build.gradle -O build.gradle

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/19wi/files/homework/scripts/hw2/compile.sh
    - sh compile.sh

stylecheck:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/19wi/files/homework/scripts/hw2/stylecheck.sh
    - sh stylecheck.sh

testPart1:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/19wi/files/homework/scripts/hw2/p1.sh
    - sh p1.sh

testPart2:
  stage: test
  script:
    - wget -q https://courses.cs.washington.edu/courses/cse373/19wi/files/homework/scripts/hw2/p2.sh
    - sh p2.sh
